In [1]:
from sklearn.datasets import load_boston
boston = load_boston()

In [2]:
type(boston)

sklearn.utils.Bunch

In [3]:
boston.keys()

dict_keys(['data', 'target', 'feature_names', 'DESCR'])

In [4]:
type(boston['data'])

numpy.ndarray

In [5]:
boston['data'][0]

array([6.320e-03, 1.800e+01, 2.310e+00, 0.000e+00, 5.380e-01, 6.575e+00,
       6.520e+01, 4.090e+00, 1.000e+00, 2.960e+02, 1.530e+01, 3.969e+02,
       4.980e+00])

In [6]:
boston['feature_names']

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

In [7]:
print(boston['DESCR'])

Boston House Prices dataset

Notes
------
Data Set Characteristics:  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive
    
    :Median Value (attribute 14) is usually the target

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pupil-teacher ratio by town
      

In [8]:
from sklearn.ensemble import RandomForestRegressor

In [9]:
clf = RandomForestRegressor()

In [10]:
clf.fit(boston['data'], boston['target'])

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [11]:
clf.score(boston['data'], boston['target'])

0.972040311820204

In [12]:
clf.n_features_

13

In [13]:
boston['data'].shape

(506, 13)

In [14]:
row = boston['data'][17]

In [15]:
row

array([  0.7842,   0.    ,   8.14  ,   0.    ,   0.538 ,   5.99  ,
        81.7   ,   4.2579,   4.    , 307.    ,  21.    , 386.75  ,
        14.67  ])

In [16]:
row.shape

(13,)

In [17]:
clf.predict(row.reshape(-1,13))

array([17.69])

In [18]:
boston['target'][17]

17.5

In [19]:
clf.predict(boston['data'][5:10])

array([27.71, 22.43, 23.17, 16.14, 18.42])

In [20]:
boston['target'][5:10]

array([28.7, 22.9, 27.1, 16.5, 18.9])

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
x_train, x_test, y_train, y_test = train_test_split(boston['data'], boston['target'], test_size=0.3)

In [23]:
y_test

array([14.3, 17.3, 21.6, 17.1, 15.6, 13.5, 20.4, 21.5, 25. , 15.2, 13.8,
       23.1, 21.2, 14.5, 24.3, 20. , 17.1, 36.5, 30.5, 29.8, 29.6, 23.2,
       50. , 50. , 24. , 36. , 19.6, 12.3, 22.8, 50. , 22.8, 24.3, 18.4,
       35.4, 50. , 19.9, 21.4, 29. , 12.7, 19.7, 16.4, 19.1, 23.1, 24.6,
       24.4, 22.2, 50. , 10.2, 35.4, 50. , 24.2, 33. , 20.9,  8.4, 27.1,
       32.2,  8.4, 30.3, 12.1, 18.9, 22.6, 13.1,  5.6, 30.1, 14.1, 41.7,
       13.1, 29.9, 27.5, 22.2, 50. , 18.7, 19.3, 15.4, 28.2,  9.6, 21.2,
       16. , 21.9,  7.5, 43.1, 22.6, 14.9, 22.3, 23.2, 23.4, 24. , 31.7,
       20. ,  9.5, 12.5, 26.2, 23.8, 13.3, 14.2, 20.3, 21.7, 13.6, 30.7,
       19.6, 26.6, 28. , 24.3, 20.6, 23. , 20. , 13.4, 13. , 28.7, 24.1,
       21. , 18.8, 15. , 30.8, 33.2, 13.4, 23.3, 22. , 23.2, 22.3, 16.2,
       24.4, 20.3, 37. , 20. , 20.3, 26.4, 26.6, 44.8, 20.5, 23.1, 19.5,
       25. , 19.6, 31.2, 16.5, 14.8, 50. , 15.6, 24.4, 21.4, 23.4, 33.1,
       22.4, 31.5, 24.8, 29.1, 48.8, 28.1, 21.7, 50

In [24]:
clf = RandomForestRegressor()
clf.fit(x_train, y_train)
clf.score(x_test, y_test)

0.812861183305305

In [25]:
import pandas as pd

In [26]:
df = pd.DataFrame(boston['data'], columns=boston['feature_names'])

In [27]:
df.max(axis=0)

CRIM        88.9762
ZN         100.0000
INDUS       27.7400
CHAS         1.0000
NOX          0.8710
RM           8.7800
AGE        100.0000
DIS         12.1265
RAD         24.0000
TAX        711.0000
PTRATIO     22.0000
B          396.9000
LSTAT       37.9700
dtype: float64

In [28]:
from sklearn.svm import SVR

In [29]:
clf = SVR()
clf.fit(x_train, y_train)
clf.score(x_test, y_test)

-0.08066958225039111

In [30]:
from sklearn import preprocessing
xs = preprocessing.scale(boston['data'])

In [31]:
df_2 = pd.DataFrame(xs, columns=boston['feature_names'])
df_2.max(axis=0)

CRIM       9.941735
ZN         3.804234
INDUS      2.422565
CHAS       3.668398
NOX        2.732346
RM         3.555044
AGE        1.117494
DIS        3.960518
RAD        1.661245
TAX        1.798194
PTRATIO    1.638828
B          0.441052
LSTAT      3.548771
dtype: float64

In [32]:
xs_train, xs_test, ys_train, ys_test = train_test_split(xs, boston['target'], test_size=0.3)

In [33]:
clf = SVR()
clf.fit(xs_train, ys_train)
clf.score(xs_test, ys_test)

0.6322259999280939

In [34]:
ys_train.shape

(354,)

In [36]:
from sklearn.decomposition import PCA #Principal Component Analysis

In [38]:
pca = PCA(n_components=5)
pca.fit(boston['data'])

PCA(copy=True, iterated_power='auto', n_components=5, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [39]:
xp = pca.transform(boston['data'])
xp.shape

(506, 5)

In [40]:
clf = RandomForestRegressor()
xp_train, xp_test, yp_train, yp_test = train_test_split(xp, boston['target'], test_size=0.3)
clf.fit(xp_train, yp_train)
clf.score(xp_test, yp_test)

0.4763035929850752

In [41]:
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

In [44]:
pipe = Pipeline([
    ('scale', StandardScaler()),
    ('pca', PCA(n_components=5)),
    ('svr', SVR())
])

In [45]:
pipe.fit(x_train, y_train)
pipe.score(x_test, y_test)

0.4392550736070159

In [46]:
pipe = Pipeline([
    ('scale', StandardScaler()),
    ('pca', PCA(n_components=5)),
    ('svr', RandomForestRegressor())
])

In [49]:
pipe.fit(x_train, y_train)
pipe.score(x_test, y_test)

0.6176805315508062

In [52]:
pipe.steps

[('scale', StandardScaler(copy=True, with_mean=True, with_std=True)),
 ('pca',
  PCA(copy=True, iterated_power='auto', n_components=5, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)),
 ('svr', RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
             max_features='auto', max_leaf_nodes=None,
             min_impurity_decrease=0.0, min_impurity_split=None,
             min_samples_leaf=1, min_samples_split=2,
             min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
             oob_score=False, random_state=None, verbose=0, warm_start=False))]

In [54]:
pipe.get_params()

{'memory': None,
 'pca': PCA(copy=True, iterated_power='auto', n_components=5, random_state=None,
   svd_solver='auto', tol=0.0, whiten=False),
 'pca__copy': True,
 'pca__iterated_power': 'auto',
 'pca__n_components': 5,
 'pca__random_state': None,
 'pca__svd_solver': 'auto',
 'pca__tol': 0.0,
 'pca__whiten': False,
 'scale': StandardScaler(copy=True, with_mean=True, with_std=True),
 'scale__copy': True,
 'scale__with_mean': True,
 'scale__with_std': True,
 'steps': [('scale', StandardScaler(copy=True, with_mean=True, with_std=True)),
  ('pca',
   PCA(copy=True, iterated_power='auto', n_components=5, random_state=None,
     svd_solver='auto', tol=0.0, whiten=False)),
  ('svr',
   RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
              max_features='auto', max_leaf_nodes=None,
              min_impurity_decrease=0.0, min_impurity_split=None,
              min_samples_leaf=1, min_samples_split=2,
              min_weight_fraction_leaf=0.0, n_estimators=10, n_

In [55]:
pipe.set_params(svr__min_samples_leaf=2)

Pipeline(memory=None,
     steps=[('scale', StandardScaler(copy=True, with_mean=True, with_std=True)), ('pca', PCA(copy=True, iterated_power='auto', n_components=5, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)), ('svr', RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_fea...timators=10, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False))])

In [56]:
pipe.get_params()

{'memory': None,
 'pca': PCA(copy=True, iterated_power='auto', n_components=5, random_state=None,
   svd_solver='auto', tol=0.0, whiten=False),
 'pca__copy': True,
 'pca__iterated_power': 'auto',
 'pca__n_components': 5,
 'pca__random_state': None,
 'pca__svd_solver': 'auto',
 'pca__tol': 0.0,
 'pca__whiten': False,
 'scale': StandardScaler(copy=True, with_mean=True, with_std=True),
 'scale__copy': True,
 'scale__with_mean': True,
 'scale__with_std': True,
 'steps': [('scale', StandardScaler(copy=True, with_mean=True, with_std=True)),
  ('pca',
   PCA(copy=True, iterated_power='auto', n_components=5, random_state=None,
     svd_solver='auto', tol=0.0, whiten=False)),
  ('svr',
   RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
              max_features='auto', max_leaf_nodes=None,
              min_impurity_decrease=0.0, min_impurity_split=None,
              min_samples_leaf=2, min_samples_split=2,
              min_weight_fraction_leaf=0.0, n_estimators=10, n_

In [57]:
import pickle

In [58]:
with open('model.pickle', 'wb') as out:
    pickle.dump(pipe, out)

In [59]:
with open('model.pickle', 'rb') as fp:
    pipe1 = pickle.load(fp)

In [60]:
pipe1.get_params()

{'memory': None,
 'pca': PCA(copy=True, iterated_power='auto', n_components=5, random_state=None,
   svd_solver='auto', tol=0.0, whiten=False),
 'pca__copy': True,
 'pca__iterated_power': 'auto',
 'pca__n_components': 5,
 'pca__random_state': None,
 'pca__svd_solver': 'auto',
 'pca__tol': 0.0,
 'pca__whiten': False,
 'scale': StandardScaler(copy=True, with_mean=True, with_std=True),
 'scale__copy': True,
 'scale__with_mean': True,
 'scale__with_std': True,
 'steps': [('scale', StandardScaler(copy=True, with_mean=True, with_std=True)),
  ('pca',
   PCA(copy=True, iterated_power='auto', n_components=5, random_state=None,
     svd_solver='auto', tol=0.0, whiten=False)),
  ('svr',
   RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
              max_features='auto', max_leaf_nodes=None,
              min_impurity_decrease=0.0, min_impurity_split=None,
              min_samples_leaf=2, min_samples_split=2,
              min_weight_fraction_leaf=0.0, n_estimators=10, n_

In [61]:
pipe1.score(x_test, y_test)

0.6176805315508062