In [2]:
from sklearn.datasets import load_boston
boston = load_boston()

In [3]:
type(boston)

sklearn.utils.Bunch

In [4]:
boston.keys()

dict_keys(['data', 'target', 'feature_names', 'DESCR'])

In [5]:
type(boston['data'])

numpy.ndarray

In [6]:
boston['data'][0]

array([6.320e-03, 1.800e+01, 2.310e+00, 0.000e+00, 5.380e-01, 6.575e+00,
       6.520e+01, 4.090e+00, 1.000e+00, 2.960e+02, 1.530e+01, 3.969e+02,
       4.980e+00])

In [7]:
boston['feature_names']

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

In [8]:
print(boston['DESCR'])

Boston House Prices dataset

Notes
------
Data Set Characteristics:  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive
    
    :Median Value (attribute 14) is usually the target

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pupil-teacher ratio by town
      

In [9]:
from sklearn.ensemble import RandomForestRegressor

In [10]:
clf = RandomForestRegressor()

In [11]:
clf.fit(boston['data'], boston['target'])

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [12]:
clf.score(boston['data'], boston['target'])

0.9737710260425334

In [13]:
clf.n_features_

13

In [14]:
boston['data'].shape

(506, 13)

In [15]:
row = boston['data'][17]

In [16]:
row

array([  0.7842,   0.    ,   8.14  ,   0.    ,   0.538 ,   5.99  ,
        81.7   ,   4.2579,   4.    , 307.    ,  21.    , 386.75  ,
        14.67  ])

In [17]:
row.shape

(13,)

In [18]:
clf.predict(row.reshape(-1,13))

array([17.28])

In [19]:
boston['target'][17]

17.5

In [20]:
clf.predict(boston['data'][5:10])

array([27.84, 22.09, 24.62, 16.85, 19.27])

In [21]:
boston['target'][5:10]

array([28.7, 22.9, 27.1, 16.5, 18.9])

In [22]:
from sklearn.model_selection import train_test_split

In [31]:
x_train, x_test, y_train, y_test = train_test_split(boston['data'], boston['target'], test_size=0.3)

In [35]:
y_test

array([29.1, 17.4, 24.2, 13.4, 18.1, 10.9, 19. , 10.5, 15. , 23.1, 20.4,
       23.7, 16. , 31.7, 17.8, 19.3, 17.9,  8.1, 24.4, 14.3, 20.7, 15.6,
       50. , 37.3, 17.5, 10.8, 11.5, 31.2, 21.9, 19.6, 50. , 29.1, 11. ,
       21.4, 21. , 17.1,  5. , 22. , 19.1, 24.8, 18.7, 37.6, 21.1, 13.8,
       23.9, 20. , 15.4, 19.8, 20.3, 13.1, 23. , 21.1, 36.1,  8.8, 29.6,
       19.5, 20. , 29.9, 22.4, 20.6, 18.5, 36.2, 37.2, 33.1, 23.9, 18.3,
       21.9, 14.2, 12.3,  9.7, 29. , 22.3, 11.7, 17.2, 16.7, 23.1, 32. ,
       33.1, 26.2, 13.8, 22.8, 13. , 23.6, 18.5, 20.9, 19.9, 23.2, 31.5,
       31.6, 23.7, 20.8,  5. , 22.8, 43.1, 21.2, 18.9, 19.4, 18.9, 23. ,
       37. , 26.5, 21.2,  8.4,  7.2, 50. , 13.2, 10.5, 32.9, 29. , 12.8,
       21.2, 32.4, 20.6, 20.7, 25.1, 12.7, 28.7, 22.6, 20.4, 21.5, 19.6,
       23.1, 24.4, 22. , 44. , 27.5, 17.2, 17.8, 22.6, 17.1, 20. , 27.5,
       13.8, 19.3, 24.1, 50. , 15.1, 21.4, 20.8, 24.5, 18.4, 22.6, 27.1,
       20.3, 30.1, 20.5, 18.5, 33.8, 22.4, 16.1, 21

In [39]:
clf = RandomForestRegressor()
clf.fit(x_train, y_train)
clf.score(x_test, y_test)

0.7884441014497056

In [38]:
clf.fit?