In [1]:
import numpy as np

In [17]:
v1 = np.reshape(np.arange(12), (3,4))
print(v1)
print("row", v1[2])
print("column", v1[:,1])
print("value", v1[2,1])
print("range_row_2", v1[2,0:3])
print("range_Part_ofrow_2", v1[0:1,0:3])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
row [ 8  9 10 11]
column [1 5 9]
value 9
range_row_2 [ 8  9 10]
range_Part_ofrow_2 [[0 1 2]]


In [30]:
v2 = np.reshape(np.arange(120), (15,8))
print(v2)
print("row 2", v2[2])
print("subset", v2[3:8, 4:8])

[[  0   1   2   3   4   5   6   7]
 [  8   9  10  11  12  13  14  15]
 [ 16  17  18  19  20  21  22  23]
 [ 24  25  26  27  28  29  30  31]
 [ 32  33  34  35  36  37  38  39]
 [ 40  41  42  43  44  45  46  47]
 [ 48  49  50  51  52  53  54  55]
 [ 56  57  58  59  60  61  62  63]
 [ 64  65  66  67  68  69  70  71]
 [ 72  73  74  75  76  77  78  79]
 [ 80  81  82  83  84  85  86  87]
 [ 88  89  90  91  92  93  94  95]
 [ 96  97  98  99 100 101 102 103]
 [104 105 106 107 108 109 110 111]
 [112 113 114 115 116 117 118 119]]
row 2 [16 17 18 19 20 21 22 23]
subset [[28 29 30 31]
 [36 37 38 39]
 [44 45 46 47]
 [52 53 54 55]
 [60 61 62 63]]
