In [1]:
import numpy as np

In [2]:
np.arange.__class__

builtin_function_or_method

In [3]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(0,10, 2)

array([0, 2, 4, 6, 8])

In [5]:
np.arange(1,10, 2)

array([1, 3, 5, 7, 9])

In [6]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [7]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
np.arange(0,10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [9]:
np.random.rand(10)

array([0.65912663, 0.4613453 , 0.8674821 , 0.46183066, 0.19620367,
       0.2435681 , 0.2811247 , 0.4537109 , 0.82121071, 0.63893007])

In [10]:
a = [1, 2, 3, 4, 5]
a.__class__

list

In [11]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [12]:
x=np.genfromtxt('data/numbers.csv', delimiter=',', dtype='int32')
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 12, 35, 34],
       [ 4, 56, 74, 33]])

In [13]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8, 10, 12, 35, 34,  4, 56, 74, 33])

In [14]:
x.reshape(2,8)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [10, 12, 35, 34,  4, 56, 74, 33]])

In [15]:
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 12, 35, 34],
       [ 4, 56, 74, 33]])

In [16]:
y = np.arange(1,17).reshape(4,4)

In [17]:
y

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [18]:
x*y

array([[   1,    4,    9,   16],
       [  25,   36,   49,   64],
       [  90,  120,  385,  408],
       [  52,  784, 1110,  528]])

In [19]:
x+y

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [19, 22, 46, 46],
       [17, 70, 89, 49]])

In [20]:
x**2

array([[   1,    4,    9,   16],
       [  25,   36,   49,   64],
       [ 100,  144, 1225, 1156],
       [  16, 3136, 5476, 1089]], dtype=int32)

In [21]:
x**y

array([[          1,           4,          27,         256],
       [       3125,       46656,      823543,    16777216],
       [ 1000000000,  1787822080,  1955950683,  -802418688],
       [   67108864,           0,  1765179392, -1831214591]], dtype=int32)

In [22]:
x*5

array([[  5,  10,  15,  20],
       [ 25,  30,  35,  40],
       [ 50,  60, 175, 170],
       [ 20, 280, 370, 165]])

In [23]:
x+4

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [14, 16, 39, 38],
       [ 8, 60, 78, 37]])

In [24]:
x//3

array([[ 0,  0,  1,  1],
       [ 1,  2,  2,  2],
       [ 3,  4, 11, 11],
       [ 1, 18, 24, 11]], dtype=int32)

In [25]:
x/3

array([[ 0.33333333,  0.66666667,  1.        ,  1.33333333],
       [ 1.66666667,  2.        ,  2.33333333,  2.66666667],
       [ 3.33333333,  4.        , 11.66666667, 11.33333333],
       [ 1.33333333, 18.66666667, 24.66666667, 11.        ]])

In [26]:
x%y

array([[ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 1,  2,  2, 10],
       [ 4,  0, 14,  1]], dtype=int32)

In [27]:
w = np.arange(1, 33, 2)

In [28]:
w

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31])

In [29]:
len(w)

16

In [30]:
x.transpose()

array([[ 1,  5, 10,  4],
       [ 2,  6, 12, 56],
       [ 3,  7, 35, 74],
       [ 4,  8, 34, 33]])

In [31]:
x.reshape(2,8)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [10, 12, 35, 34,  4, 56, 74, 33]])

In [32]:
x.shape

(4, 4)

In [34]:
np.concatenate?