In [1]:
import numpy as np

In [11]:
v1 = np.reshape(np.arange(42), (7,6))
print("v1", v1)
#v2 = v1%2
#print(v2)
#print(v1[(1,2,3),])
#v1[v1/2==0]
#v2=v1/2==0
#v1[True]
v2=np.array([1,3,5])
print("v2", v1[v2])
#y[np.array([0,2,4]), np.array([0,1,2])]
v3=v1[np.array([1,3,5]), np.array([1,3,5])]
print(v3)

v1 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]
 [36 37 38 39 40 41]]
v2 [[ 6  7  8  9 10 11]
 [18 19 20 21 22 23]
 [30 31 32 33 34 35]]
[ 7 21 35]


In [13]:
v1>20
v1[v1>20]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
       38, 39, 40, 41])

In [29]:
w1 = np.array([False, False, True, False, True, True, False])
print(v1[w1])
print(v1[np.array([2,4,5])])
print(v1[[2,4,5]])
print(v1[[2,4,5],[2,4,5]])

[[12 13 14 15 16 17]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
[[12 13 14 15 16 17]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
[[12 13 14 15 16 17]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
[14 28 35]
