In [3]:
2 ** 1000

10715086071862673209484250490600018105614048117055336074437503883703510511249361224931983788156958581275946729175531468251871452856923140435984577574698574803934567774824230985421074605062371141877954182153046474983581941267398767559165543946077062914571196477686542167660429831652624386837205668069376

In [4]:
import numpy as np

In [5]:
np.int64(2) ** 100

0

In [6]:
arr = np.array([1, 2, 3], dtype=np.int64)

In [7]:
v1 = np.random.rand(1000000)
v2 = np.random.rand(1000000)

In [8]:
%time v1 * v2

CPU times: user 2.88 ms, sys: 3.87 ms, total: 6.75 ms
Wall time: 6.44 ms


array([ 0.21768167,  0.16189611,  0.05379049, ...,  0.37285372,
        0.13816981,  0.92795428])

In [9]:
v3 = np.array([1,2,3,4])
v4 = np.array([5,6,7,8])
print (v3 * v4)
print (np.dot(v3, v4))
print (v3 @ v4)

[ 5 12 21 32]
70
70


In [10]:
v5 = np.arange(2,100,2)
#v6 = np.random.rand
print (v5)
print (v5.size)
v6 = np.reshape(v5, (7,7))
print(v6)
#np.reshape(v6, (7,7))
v5[4] = 20
print(v5)
print(v6)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50
 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96 98]
49
[[ 2  4  6  8 10 12 14]
 [16 18 20 22 24 26 28]
 [30 32 34 36 38 40 42]
 [44 46 48 50 52 54 56]
 [58 60 62 64 66 68 70]
 [72 74 76 78 80 82 84]
 [86 88 90 92 94 96 98]]
[ 2  4  6  8 20 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50
 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96 98]
[[ 2  4  6  8 20 12 14]
 [16 18 20 22 24 26 28]
 [30 32 34 36 38 40 42]
 [44 46 48 50 52 54 56]
 [58 60 62 64 66 68 70]
 [72 74 76 78 80 82 84]
 [86 88 90 92 94 96 98]]


In [11]:
v6.transpose()

array([[ 2, 16, 30, 44, 58, 72, 86],
       [ 4, 18, 32, 46, 60, 74, 88],
       [ 6, 20, 34, 48, 62, 76, 90],
       [ 8, 22, 36, 50, 64, 78, 92],
       [20, 24, 38, 52, 66, 80, 94],
       [12, 26, 40, 54, 68, 82, 96],
       [14, 28, 42, 56, 70, 84, 98]])

In [13]:
np.dot?